[project]
name = "ad-omics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.3",
    "pyreadr>=0.5.3",
    "scanpy>=1.11.1",
    "torch>=2.7.0",
]

[dependency-groups]
dev = [
    "gpustat>=1.1.1",
    "ipdb>=0.13.13",
    "ipykernel>=6.29.5",
]

[tool.setuptools]
packages = ["data", "models", "trainer"]
